### ISSUE TITLE
Création de sites depuis les formulaires ODK

### ISSUE THREAD

**Issue by lpojgc** [PnX-SI/odk2gn#9]
Bonjour,
> Actuellement seul les niveaux "visites" et "observations" sont implémentés. Il n'est pas possible de créer des sites à partir des formulaires ODK.

Est-ce qu'il y avait des contraintes dans la gestion des créations de sites ou est-ce simplement pour des questions de temps que vous n'avez pas fait ces dev ?
Nous nous sommes lancés dans la création de formulaires ODK avec création de sites mais on coince sur l'import de ces formulaires du coup...
Merci d'avance

**Comment by camillemonchicourt** [comment]
Question de temps, de complexité et surtout de complexité car on a retenu pour cette première version que la saisie mobile était prioritairement utile pour des visites de sites prédéfinis en amont.

Mais pouvoir aussi créer des sites serait une évolution intéressante.

**Comment by TheoLechemia** [comment]
Fait
